# Generated by Django 5.0.3 on 2024-04-05 16:18

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('roll_num', models.IntegerField()),
                ('father_name', models.CharField(max_length=254)),
                ('mother_name', models.CharField(max_length=254)),
                ('mobile_num', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=254)),
                ('father_image', models.ImageField(upload_to='blog')),
                ('mother_image', models.ImageField(upload_to='blog')),
                ('student_image', models.ImageField(upload_to='blog')),
            ],
        ),
    ]
