# Generated by Django 5.0.3 on 2024-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='mobile_num',
            new_name='phone',
        ),
    ]
