# Generated by Django 5.0.3 on 2024-04-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_mobile_num_todomodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='father_image',
            field=models.ImageField(upload_to='media/blog'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='mother_image',
            field=models.ImageField(upload_to='media/blog'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='student_image',
            field=models.ImageField(upload_to='media/blog'),
        ),
    ]
