# Generated by Django 5.0.3 on 2024-04-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todomodel_father_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='father_image',
            field=models.ImageField(upload_to='media/blog'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='mother_image',
            field=models.ImageField(upload_to='media/blog'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='student_image',
            field=models.ImageField(upload_to='media/blog'),
        ),
    ]
