# Generated by Django 5.0.3 on 2024-06-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_todomodel_father_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
